In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#Loading the Data set 
df = pd.read_excel("../data/Pizza_Sales_Dataset.xlsx")

In [7]:
df.head()

,Date,Pizza_Name,Category,Pizza_Code,Price_USD,Sales,Unsold,Revenue,Rating
0,01 January 2022,Deluxe,Non-Veg,4,15,61,7,915,Average Seller
1,01 January 2022,Double Cheese,Veg,5,9,68,9,612,Average Seller
2,01 January 2022,Farmhouse,Veg,3,7,284,23,1988,Top Seller
3,02 January 2023,Deluxe,Non-Veg,4,15,133,9,1995,Top Seller
4,02 January 2023,Double Cheese,Veg,5,9,194,21,1746,Top Seller

In [9]:
df.shape

(61, 9)

In [12]:
df.columns.tolist()  #for loading columns in list format use tolist()

['Date',
 'Pizza_Name',
 'Category',
 'Pizza_Code',
 'Price_USD',
 'Sales',
 'Unsold',
 'Revenue',
 'Rating']

In [13]:
#info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        61 non-null     object
 1   Pizza_Name  61 non-null     object
 2   Category    61 non-null     object
 3   Pizza_Code  61 non-null     int64
 4   Price_USD   61 non-null     int64
 5   Sales       61 non-null     int64
 6   Unsold      61 non-null     int64
 7   Revenue     61 non-null     int64
 8   Rating      61 non-null     object
dtypes: int64(5), object(4)
memory usage: 4.4+ KB

In [15]:
#checking null values / missing values 
df.isnull().sum()

Date          0
Pizza_Name    0
Category      0
Pizza_Code    0
Price_USD     0
Sales         0
Unsold        0
Revenue       0
Rating        0
dtype: int64

In [16]:
#checking the duplicate value
df.duplicated().sum()

np.int64(0)

In [17]:
df["Date"] = pd.to_datetime(df["Date"])

In [21]:
#Statistcall summary 
df.describe()

,Date,Pizza_Code,Price_USD,Sales,Unsold,Revenue
count,61,61.000000,61.000000,61.000000,61.000000,61.000000
mean,2023-01-07 12:59:00.983606528,3.213115,9.885246,170.163934,13.557377,1682.409836
min,2022-01-01 00:00:00,1.000000,7.000000,50.000000,1.000000,400.000000
25%,2023-01-10 00:00:00,2.000000,7.000000,98.000000,8.000000,972.000000
50%,2023-01-25 00:00:00,3.000000,9.000000,169.000000,12.000000,1617.000000
75%,2023-02-09 00:00:00,4.000000,10.000000,238.000000,21.000000,2072.000000
max,2023-02-24 00:00:00,5.000000,15.000000,296.000000,25.000000,4335.000000
std,NaN,1.279515,3.006096,75.321794,7.340583,958.881490

In [25]:
#unique values
df["Pizza_Name"].unique().tolist()

['Deluxe', 'Double Cheese', 'Farmhouse', 'Chicago', 'Margherita']

In [27]:
df["Category"].unique().tolist()

['Non-Veg', 'Veg']

In [28]:
df["Rating"]

0     Average Seller
1     Average Seller
2         Top Seller
3         Top Seller
4         Top Seller
           ...
56        Top Seller
57        Top Seller
58        Top Seller
59        Top Seller
60        Top Seller
Name: Rating, Length: 61, dtype: object

In [30]:
df.shape

(61, 9)