In [1]:
#1) KMeans (done)
#2) DBScan (done)
#3) Apriori---->used for the bussiness pattern 
# EXAMPLE---> The standard example is market basket analysis: “customers who buy bread and butter also tend to buy milk.”
# customer      Product
#    A           Bread , Milk
#    B           Bread , Milk , Butter
#    C           Bread , Butter 
#    D           Milk , Butter
#    E           Bread , Milk , Butter
# you need to perform 3 operation in apriori

In [2]:
#1) Support--->element frequently repeated / Total customer comming to the shop
#support(A) = Repeated element / Total Transcation
#support(Bread)  =     4/5 * 100----->80% 
#support(Milk)   =     4/5 * 100----->80% 
#support(Butter) =     4/5 * 100----->80%
#each produt selling percentage 

#but we need to calulate in once ---> 
#support (A,B) = pair of Repeated Element / Total Tanscation
#support(Bread,Milk)   = 3/5*100--->60%
#support(Millk,Butter) = 3/5*100--->60%
#support(Bread,Butter) = 3/5*100--->60

#support(A,B,C) = Repeated Element / Total Tanscation
#support(Bread , Milk , Butter)  = 2/5*100 = 40%

#if the pair of element is less than 60% then remove the pair
# support >= min_support

In [3]:
#2) Confindence
# if i purchsing two two element together then fist elment how many times it is repeated 
# confidence(A,B) =  Both elment frequence / element(A)

# Bread and Milk ---> 3/4*100--->75%
# Milk and Butter---> 3/4*100--->75%
# Butter and Bread--> 3/4*100--->75%

In [4]:
#3) Lift-----> Confidence(A,B) / Support(B)
#                Bread , Milk / support(Milk) ----> 0.75/0.8
#                Milk , Butter / support(Butter)--> 0.75/0.8
#                Butter , Bread/ support(Bread)---> 0.75/0.8
# the lift value is 0.975

# Lift > 1: positive association (bought together more than by chance)
# Lift = 1: independent
# Lift < 1: negative association (bought together less than by chance)

In [5]:
# if you want to work in bussiness analysis then you need to do this steps

In [7]:
import pandas as pd 
data1 = {"Laptop":[1,1,1,0,1,1],
         "Bag" : [1,1,1,1,1,1],
         "Charger" : [0,0,1,1,0,1]
        }
df1 = pd.DataFrame(data1)
df1

   Laptop  Bag  Charger
0       1    1        0
1       1    1        0
2       1    1        1
3       0    1        1
4       1    1        0
5       1    1        1

In [2]:
%pip install mlxtend

Collecting mlxtend
  Using cached mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in c:\users\win-11\anaconda3\lib\site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in c:\users\win-11\anaconda3\lib\site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in c:\users\win-11\anaconda3\lib\site-packages (from mlxtend) (2.3.3)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Using cached scikit_learn-1.9.1-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Using cached matplotlib-3.11.2-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: joblib>=1.5.2 in c:\users\win-11\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=9 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\win-11\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\win-11\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\win-11\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\win-11\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\win-11\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\win-11\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Using cached mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
Downloading matplotlib-3.11.2-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   -- ------------------------------------- 0.5/9.3 MB 38.5 kB/s eta 0:03:50
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   --- ------------------------------------ 0.8/9.3 MB 43.6 kB/s eta 0:03:17
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ---- ----------------------------------- 1.0/9.3 MB 45.6 kB/s eta 0:03:03
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ----- ---------------------------------- 1.3/9.3 MB 50.3 kB/s eta 0:02:40
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------ --------------------------------- 1.6/9.3 MB 57.3 kB/s eta 0:02:16
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   ------- -------------------------------- 1.8/9.3 MB 65.0 kB/s eta 0:01:56
   -------- ------------------------------- 2.1/9.3 MB 68.8 kB/s eta 0:01:46
   -------- ------------------------------- 2.1/9.3 MB 68.8 kB/s eta 0:01:46
   -------- ------------------------------- 2.1/9.3 MB 68.8 kB/s eta 0:01:46
   -------- ------------------------------- 2.1/9.3 MB 68.8 kB/s eta 0:01:46
   -------- ------------------------------- 2.1/9.3 MB 68.8 kB/s eta 0:01:46
   -------- ------------------------------- 2.1/9.3 MB 68.8 kB/s eta 0:01:46
   ---------- ----------------------------- 2.4/9.3 MB 74.9 kB/s eta 0:01:34
   ---------- ----------------------------- 2.4/9.3 MB 74.9 kB/s eta 0:01:34
   ---------- ----------------------------- 2.4/9.3 MB 74.9 kB/s eta 0:01:34
   ---------- ----------------------------- 2.4/9.3 MB 74.9 kB/s eta 0:01:34
   ---------- ----------------------------- 2.4/9.3 MB 74.9 kB/s eta 0:01:34
   ---------- ----------------------------- 2.4/9.3 MB 74.9 kB/s eta 0:01:34
   ----------- ---------------------------- 2.6/9.3 MB 80.5 kB/s eta 0:01:24
   ----------- ---------------------------- 2.6/9.3 MB 80.5 kB/s eta 0:01:24
   ------------ --------------------------- 2.9/9.3 MB 88.0 kB/s eta 0:01:14
   ------------ --------------------------- 2.9/9.3 MB 88.0 kB/s eta 0:01:14
   ------------ --------------------------- 2.9/9.3 MB 88.0 kB/s eta 0:01:14
   ------------ --------------------------- 2.9/9.3 MB 88.0 kB/s eta 0:01:14
   ------------ --------------------------- 2.9/9.3 MB 88.0 kB/s eta 0:01:14
   ------------ --------------------------- 2.9/9.3 MB 88.0 kB/s eta 0:01:14
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58
   ------------- -------------------------- 3.1/9.3 MB 108.5 kB/s eta 0:00:58

In [8]:
from mlxtend.frequent_patterns import apriori, association_rules

In [9]:
device = apriori(df1,min_support = 0.5 , use_colnames = True)
device

C:\Users\Win-11\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support        itemsets
0  0.833333        (Laptop)
1  1.000000           (Bag)
2  0.500000       (Charger)
3  0.833333   (Laptop, Bag)
4  0.500000  (Charger, Bag)

In [16]:
rules = association_rules(device , metric = 'confidence' , min_threshold   = 0.5)
print(rules[['antecedents' , 'consequents' , 'support' , 'confidence' , 'lift']])

  antecedents consequents   support  confidence  lift
0    (Laptop)       (Bag)  0.833333    1.000000   1.0
1       (Bag)    (Laptop)  0.833333    0.833333   1.0
2   (Charger)       (Bag)  0.500000    1.000000   1.0
3       (Bag)   (Charger)  0.500000    0.500000   1.0

C:\Users\Win-11\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:184: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)