In [1]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
from sklearn.model_selection import train_test_split
from  sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import  RandomForestRegressor

In [5]:
from sklearn.metrics import (mean_absolute_error , 
mean_squared_error , r2_score)

In [6]:
df = pd.read_excel("../data/Pizza_Sales_Dataset.xlsx")

In [7]:
df.head()

,Date,Pizza_Name,Category,Pizza_Code,Price_USD,Sales,Unsold,Revenue,Rating
0,01 January 2022,Deluxe,Non-Veg,4,15,61,7,915,Average Seller
1,01 January 2022,Double Cheese,Veg,5,9,68,9,612,Average Seller
2,01 January 2022,Farmhouse,Veg,3,7,284,23,1988,Top Seller
3,02 January 2023,Deluxe,Non-Veg,4,15,133,9,1995,Top Seller
4,02 January 2023,Double Cheese,Veg,5,9,194,21,1746,Top Seller

In [9]:
df.shape

(61, 9)

In [10]:
# Can we predict the number of pizzas sold using information available about the pizza and sale?
target = "Sales"

In [15]:
# Create date features
df["Date"] = pd.to_datetime(df["Date"])
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day
df["Day_Name"] = df["Date"].dt.day_name()

In [20]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Day_of_Week"] = df["Date"].dt.dayofweek

In [23]:
X = df[
    [
        "Pizza_Name" , 
        "Category",
        "Pizza_Code",
        "Price_USD",
        "Year",
        "Month",
        "Day" , 
        "Day_of_Week"
    ]
    ]

y = df["Sales"]

In [24]:
X.head()

,Pizza_Name,Category,Pizza_Code,Price_USD,Year,Month,Day,Day_of_Week
0,Deluxe,Non-Veg,4,15,2022,1,1,5
1,Double Cheese,Veg,5,9,2022,1,1,5
2,Farmhouse,Veg,3,7,2022,1,1,5
3,Deluxe,Non-Veg,4,15,2023,1,2,0
4,Double Cheese,Veg,5,9,2023,1,2,0

In [25]:
y.head()

0     61
1     68
2    284
3    133
4    194
Name: Sales, dtype: int64

In [ ]:
X_train , X_test , Y_train , Y_test = train_set_split(
    X , 
    y , 
    test_size = 0.2,
    random_s